version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: runners-mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_DATABASE=runners_api
      - MYSQL_USER=postgres
      - MYSQL_PASSWORD=docker
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
